### ISSUE TITLE
Localhost:3000 fails to display content

### ISSUE THREAD

**Issue by sunburntcat** [henriquemacedo/k-dash#1]
<img width="793" alt="Screen Shot 2021-08-02 at 10 27 55 AM" src="https://user-images.githubusercontent.com/32531379/127886124-ff1196c7-193c-48f7-b741-f14c9d50ec07.png">

Happens on both Chrome and Safari with no console messages displayed except for warning "GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode."

OS Used:  Ubuntu 18.04
Browsers:  Firefox and Chrome
NPM version:   6.14.14
Next.js version:  11.0.1

Commands run:
$ npm run dev
--> Successful start of localhost on 3000
--> No page content

**Comment by ickas** [comment]
Hey, @sunburntcat  👋

I do a clean install `npm install && npm run dev` here and everything works fine. I'm trying to understand what can happen on your side, but I'm not able to replicate the issue. Also, everything looks good on deploy on the Netlify server side ([server-log.txt](https://github.com/henriquemacedo/k-dash/files/6925802/server-log.txt)).

When you do the `npm install` everything install well?

**Comment by ickas** [comment]
@sunburntcat finally I understand the problem, and now it's fixed. 🎉

`if (!mountedComponent) return <div />;`

Sometimes, he was trying to access the cache before the loading to see whats your last theme choice is (light or dark).
